# build information
package = 'nebula/cmd/api'
build_args = []

# filter for files to be watched
filter = "^.*\\.(go)$"

# max events that can be sent in one tick of the watcher
max_events = 1

# how long between events to wait before considering it a change (in ms)
debounce_time = 250

# print watched files when the watcher starts, mainly for debugging
print_watched = false

# the directories to be watched
directories = [
    'pkg/api',
    'cmd/api'
]
